# Generated by Django 4.2.23 on 2025-08-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('exercise_level', models.CharField(max_length=50)),
                ('diet_type', models.CharField(max_length=50)),
                ('sleep_hours', models.FloatField()),
                ('stress_level', models.CharField(max_length=50)),
                ('mental_health_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('work_hours_per_week', models.IntegerField()),
                ('screen_time_per_day', models.FloatField()),
                ('social_interaction_score', models.FloatField()),
                ('happiness_score', models.FloatField()),
            ],
        ),
    ]
